# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\TilePuzzleSolverGUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def __init__(self, controller):
        self.controller = controller

    def setupUi(self, MainWindow):

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(829, 744)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(700, 700))
        MainWindow.setAnimated(True)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(245, 245, 245);\n"
                                         "")
        self.centralwidget.setObjectName("centralwidget")

        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")

        self.container = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.container.sizePolicy().hasHeightForWidth())
        self.container.setSizePolicy(sizePolicy)
        self.container.setMaximumSize(QtCore.QSize(700, 700))
        self.container.setStyleSheet("")
        self.container.setObjectName("container")

        self.gridLayout_2 = QtWidgets.QGridLayout(self.container)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(5)
        self.gridLayout_2.setObjectName("gridLayout_2")

        self.goal_state = QtWidgets.QWidget(self.container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.goal_state.sizePolicy().hasHeightForWidth())
        self.goal_state.setSizePolicy(sizePolicy)
        self.goal_state.setStyleSheet("border: none;")
        self.goal_state.setObjectName("goal_state")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.goal_state)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.goal = QtWidgets.QWidget(self.goal_state)
        self.goal.setMinimumSize(QtCore.QSize(200, 200))
        self.goal.setObjectName("goal")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.goal)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.g4 = QtWidgets.QLineEdit(self.goal)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(22)
        self.g4.setFont(font)
        self.g4.setStyleSheet("background: #ffffff; border: 2px solid red;")
        self.g4.setMaxLength(1)
        self.g4.setAlignment(QtCore.Qt.AlignCenter)
        self.g4.setClearButtonEnabled(False)
        self.g4.setObjectName("g4")
        self.gridLayout_7.addWidget(self.g4, 3, 1, 1, 1)
        self.g8 = QtWidgets.QLineEdit(self.goal)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(22)
        self.g8.setFont(font)
        self.g8.setStyleSheet("background: #ffffff; border: 2px solid red;")
        self.g8.setMaxLength(1)
        self.g8.setAlignment(QtCore.Qt.AlignCenter)
        self.g8.setClearButtonEnabled(False)
        self.g8.setObjectName("g8")
        self.gridLayout_7.addWidget(self.g8, 4, 2, 1, 1)
        self.g2 = QtWidgets.QLineEdit(self.goal)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(22)
        self.g2.setFont(font)
        self.g2.setStyleSheet("background: #ffffff; border: 2px solid red;")
        self.g2.setMaxLength(1)
        self.g2.setAlignment(QtCore.Qt.AlignCenter)
        self.g2.setClearButtonEnabled(False)
        self.g2.setObjectName("g2")
        self.gridLayout_7.addWidget(self.g2, 2, 2, 1, 1)
        self.g5 = QtWidgets.QLineEdit(self.goal)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(22)
        self.g5.setFont(font)
        self.g5.setStyleSheet("background: #ffffff; border: 2px solid red;")
        self.g5.setMaxLength(1)
        self.g5.setAlignment(QtCore.Qt.AlignCenter)
        self.g5.setClearButtonEnabled(False)
        self.g5.setObjectName("g5")
        self.gridLayout_7.addWidget(self.g5, 3, 2, 1, 1)
        self.g7 = QtWidgets.QLineEdit(self.goal)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(22)
        self.g7.setFont(font)
        self.g7.setStyleSheet("background: #ffffff; border: 2px solid red;")
        self.g7.setMaxLength(1)
        self.g7.setAlignment(QtCore.Qt.AlignCenter)
        self.g7.setClearButtonEnabled(False)
        self.g7.setObjectName("g7")
        self.gridLayout_7.addWidget(self.g7, 4, 1, 1, 1)
        self.g1 = QtWidgets.QLineEdit(self.goal)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(22)
        self.g1.setFont(font)
        self.g1.setStyleSheet("background: #ffffff; border: 2px solid red;")
        self.g1.setMaxLength(1)
        self.g1.setAlignment(QtCore.Qt.AlignCenter)
        self.g1.setClearButtonEnabled(False)
        self.g1.setObjectName("g1")
        self.gridLayout_7.addWidget(self.g1, 2, 1, 1, 1)
        self.g3 = QtWidgets.QLineEdit(self.goal)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(22)
        self.g3.setFont(font)
        self.g3.setStyleSheet("background: #ffffff; border: 2px solid red;")
        self.g3.setMaxLength(1)
        self.g3.setAlignment(QtCore.Qt.AlignCenter)
        self.g3.setClearButtonEnabled(False)
        self.g3.setObjectName("g3")
        self.gridLayout_7.addWidget(self.g3, 3, 0, 1, 1)
        self.g6 = QtWidgets.QLineEdit(self.goal)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(22)
        self.g6.setFont(font)
        self.g6.setStyleSheet("background: #ffffff; border: 2px solid red;")
        self.g6.setMaxLength(1)
        self.g6.setAlignment(QtCore.Qt.AlignCenter)
        self.g6.setClearButtonEnabled(False)
        self.g6.setObjectName("g6")
        self.gridLayout_7.addWidget(self.g6, 4, 0, 1, 1)
        self.g0 = QtWidgets.QLineEdit(self.goal)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(22)
        self.g0.setFont(font)
        self.g0.setStyleSheet("background: #ffffff; border: 2px solid red;")
        self.g0.setMaxLength(1)
        self.g0.setAlignment(QtCore.Qt.AlignCenter)
        self.g0.setClearButtonEnabled(False)
        self.g0.setObjectName("g0")
        self.gridLayout_7.addWidget(self.g0, 2, 0, 1, 1)
        self.goalLabel = QtWidgets.QLabel(self.goal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.goalLabel.sizePolicy().hasHeightForWidth())
        self.goalLabel.setSizePolicy(sizePolicy)
        self.goalLabel.setMinimumSize(QtCore.QSize(40, 20))
        self.goalLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        self.goalLabel.setFont(font)
        self.goalLabel.setScaledContents(False)
        self.goalLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.goalLabel.setObjectName("goalLabel")
        self.gridLayout_7.addWidget(self.goalLabel, 1, 0, 1, 3)
        self.gridLayout_5.addWidget(self.goal, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.goal_state, 0, 1, 1, 1)
        self.sim = QtWidgets.QWidget(self.container)
        self.sim.setAutoFillBackground(False)
        self.sim.setStyleSheet("border: none;")
        self.sim.setObjectName("sim")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.sim)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.controls = QtWidgets.QWidget(self.sim)
        self.controls.setMinimumSize(QtCore.QSize(0, 137))
        self.controls.setObjectName("controls")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.controls)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.toggleManualControl = QtWidgets.QPushButton(self.controls)
        self.toggleManualControl.setMinimumSize(QtCore.QSize(0, 30))
        self.toggleManualControl.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        self.toggleManualControl.setFont(font)
        self.toggleManualControl.setStyleSheet("background: #00aaff;\n"
                                               "color:white;\n"
                                               "border-style: outset;\n"
                                               "border-width: 1px;\n"
                                               "border-radius: 15px;\n"
                                               "border-color: black;\n"
                                               "padding: 4px;")
        self.toggleManualControl.setAutoRepeat(False)
        self.toggleManualControl.setObjectName("toggleManualControl")
        self.gridLayout_9.addWidget(self.toggleManualControl, 1, 1, 1, 3)
        self.nextButton = QtWidgets.QPushButton(self.controls)
        self.nextButton.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        self.nextButton.setFont(font)
        self.nextButton.setStyleSheet("background: #00aaff;\n"
                                      "color:white;\n"
                                      "border-style: outset;\n"
                                      "border-width: 1px;\n"
                                      "border-radius: 15px;\n"
                                      "border-color: black;\n"
                                      "padding: 4px;")
        self.nextButton.setAutoRepeat(False)
        self.nextButton.setObjectName("nextButton")
        self.gridLayout_9.addWidget(self.nextButton, 0, 4, 1, 1)
        self.previousButton = QtWidgets.QPushButton(self.controls)
        self.previousButton.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        self.previousButton.setFont(font)
        self.previousButton.setStyleSheet("background: #00aaff;\n"
                                          "color:white;\n"
                                          "border-style: outset;\n"
                                          "border-width: 1px;\n"
                                          "border-radius: 15px;\n"
                                          "border-color: black;\n"
                                          "padding: 4px;")
        self.previousButton.setAutoRepeat(False)
        self.previousButton.setObjectName("previousButton")
        self.gridLayout_9.addWidget(self.previousButton, 0, 0, 1, 1)
        self.pauseButton = QtWidgets.QPushButton(self.controls)
        self.pauseButton.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        self.pauseButton.setFont(font)
        self.pauseButton.setStyleSheet("background: #00aaff;\n"
                                       "color:white;\n"
                                       "border-style: outset;\n"
                                       "border-width: 1px;\n"
                                       "border-radius: 15px;\n"
                                       "border-color: black;\n"
                                       "padding: 4px;")
        self.pauseButton.setAutoRepeat(False)
        self.pauseButton.setObjectName("pauseButton")
        self.gridLayout_9.addWidget(self.pauseButton, 0, 1, 1, 1)
        self.resetButton = QtWidgets.QPushButton(self.controls)
        self.resetButton.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        self.resetButton.setFont(font)
        self.resetButton.setStyleSheet("background: #00aaff;\n"
                                       "color:white;\n"
                                       "border-style: outset;\n"
                                       "border-width: 1px;\n"
                                       "border-radius: 15px;\n"
                                       "border-color: black;\n"
                                       "padding: 4px;")
        self.resetButton.setAutoRepeat(False)
        self.resetButton.setObjectName("resetButton")
        self.gridLayout_9.addWidget(self.resetButton, 0, 3, 1, 1)

        self.startButton = QtWidgets.QPushButton(self.controls)
        self.startButton.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        self.startButton.setFont(font)
        self.startButton.setStyleSheet("background: #00aaff;\n"
                                       "color:white;\n"
                                       "border-style: outset;\n"
                                       "border-width: 1px;\n"
                                       "border-radius: 15px;\n"
                                       "border-color: black;\n"
                                       "padding: 4px;")
        self.startButton.setAutoRepeat(False)
        self.startButton.setObjectName("startButton")
        self.gridLayout_9.addWidget(self.startButton, 0, 2, 1, 1)
        self.gridLayout_3.addWidget(self.controls, 1, 0, 1, 2)
        self.output = QtWidgets.QWidget(self.sim)
        self.output.setObjectName("output")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.output)
        self.gridLayout_8.setHorizontalSpacing(5)
        self.gridLayout_8.setVerticalSpacing(30)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.out6 = QtWidgets.QLabel(self.output)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.out6.sizePolicy().hasHeightForWidth())
        self.out6.setSizePolicy(sizePolicy)
        self.out6.setMinimumSize(QtCore.QSize(50, 50))
        self.out6.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(20)
        self.out6.setFont(font)
        self.out6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.out6.setStyleSheet("background: #ffffff;\n"
                                "border: 3px solid red;")
        self.out6.setAlignment(QtCore.Qt.AlignCenter)
        self.out6.setObjectName("out6")
        self.gridLayout_8.addWidget(self.out6, 4, 2, 1, 1)
        self.out0 = QtWidgets.QLabel(self.output)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.out0.sizePolicy().hasHeightForWidth())
        self.out0.setSizePolicy(sizePolicy)
        self.out0.setMinimumSize(QtCore.QSize(50, 50))
        self.out0.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(20)
        self.out0.setFont(font)
        self.out0.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.out0.setStyleSheet("background: #ffffff;\n"
                                "border: 3px solid red;")
        self.out0.setAlignment(QtCore.Qt.AlignCenter)
        self.out0.setObjectName("out0")
        self.gridLayout_8.addWidget(self.out0, 2, 2, 1, 1)
        self.out2 = QtWidgets.QLabel(self.output)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.out2.sizePolicy().hasHeightForWidth())
        self.out2.setSizePolicy(sizePolicy)
        self.out2.setMinimumSize(QtCore.QSize(50, 50))
        self.out2.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(20)
        self.out2.setFont(font)
        self.out2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.out2.setStyleSheet("background: #ffffff;\n"
                                "border: 3px solid red;")
        self.out2.setAlignment(QtCore.Qt.AlignCenter)
        self.out2.setObjectName("out2")
        self.gridLayout_8.addWidget(self.out2, 2, 4, 1, 1)
        self.out1 = QtWidgets.QLabel(self.output)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.out1.sizePolicy().hasHeightForWidth())
        self.out1.setSizePolicy(sizePolicy)
        self.out1.setMinimumSize(QtCore.QSize(50, 50))
        self.out1.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(20)
        self.out1.setFont(font)
        self.out1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.out1.setStyleSheet("background: #ffffff;\n"
                                "border: 3px solid red;")
        self.out1.setAlignment(QtCore.Qt.AlignCenter)
        self.out1.setObjectName("out1")
        self.gridLayout_8.addWidget(self.out1, 2, 3, 1, 1)
        self.out3 = QtWidgets.QLabel(self.output)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.out3.sizePolicy().hasHeightForWidth())
        self.out3.setSizePolicy(sizePolicy)
        self.out3.setMinimumSize(QtCore.QSize(50, 50))
        self.out3.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(20)
        self.out3.setFont(font)
        self.out3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.out3.setStyleSheet("background: #ffffff;\n"
                                "border: 3px solid red;")
        self.out3.setAlignment(QtCore.Qt.AlignCenter)
        self.out3.setObjectName("out3")
        self.gridLayout_8.addWidget(self.out3, 3, 2, 1, 1)
        self.out4 = QtWidgets.QLabel(self.output)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.out4.sizePolicy().hasHeightForWidth())
        self.out4.setSizePolicy(sizePolicy)
        self.out4.setMinimumSize(QtCore.QSize(50, 50))
        self.out4.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(20)
        self.out4.setFont(font)
        self.out4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.out4.setStyleSheet("background: #ffffff;\n"
                                "border: 3px solid red;")
        self.out4.setAlignment(QtCore.Qt.AlignCenter)
        self.out4.setObjectName("out4")
        self.gridLayout_8.addWidget(self.out4, 3, 3, 1, 1)
        self.out5 = QtWidgets.QLabel(self.output)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.out5.sizePolicy().hasHeightForWidth())
        self.out5.setSizePolicy(sizePolicy)
        self.out5.setMinimumSize(QtCore.QSize(50, 50))
        self.out5.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(20)
        self.out5.setFont(font)
        self.out5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.out5.setStyleSheet("background: #ffffff;\n"
                                "border: 3px solid red;")
        self.out5.setAlignment(QtCore.Qt.AlignCenter)
        self.out5.setObjectName("out5")
        self.gridLayout_8.addWidget(self.out5, 3, 4, 1, 1)
        self.out7 = QtWidgets.QLabel(self.output)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.out7.sizePolicy().hasHeightForWidth())
        self.out7.setSizePolicy(sizePolicy)
        self.out7.setMinimumSize(QtCore.QSize(50, 50))
        self.out7.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(20)
        self.out7.setFont(font)
        self.out7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.out7.setStyleSheet("background: #ffffff;\n"
                                "border: 3px solid red;")
        self.out7.setAlignment(QtCore.Qt.AlignCenter)
        self.out7.setObjectName("out7")
        self.gridLayout_8.addWidget(self.out7, 4, 3, 1, 1)
        self.out8 = QtWidgets.QLabel(self.output)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.out8.sizePolicy().hasHeightForWidth())
        self.out8.setSizePolicy(sizePolicy)
        self.out8.setMinimumSize(QtCore.QSize(50, 50))
        self.out8.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(20)
        self.out8.setFont(font)
        self.out8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.out8.setStyleSheet("background: #ffffff;\n"
                                "border: 3px solid red;")
        self.out8.setAlignment(QtCore.Qt.AlignCenter)
        self.out8.setObjectName("out8")
        self.gridLayout_8.addWidget(self.out8, 4, 4, 1, 1)
        self.gridLayout_3.addWidget(self.output, 2, 0, 2, 2)
        self.label = QtWidgets.QLabel(self.sim)
        self.label.setMinimumSize(QtCore.QSize(0, 20))
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 10pt \"Arial Rounded MT Bold\";\n"
                                 "text-align: center;\n"
                                 "")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.gridLayout_2.addWidget(self.sim, 1, 0, 2, 2)
        self.solution = QtWidgets.QWidget(self.container)
        self.solution.setAutoFillBackground(False)
        self.solution.setStyleSheet("border: none;")
        self.solution.setObjectName("solution")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.solution)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.solution)
        self.label_3.setMinimumSize(QtCore.QSize(0, 20))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.printWindow = QtWidgets.QTextBrowser(self.solution)
        self.printWindow.setStyleSheet("background:#ffffff;\n"
                                       "text-align: center;\n"
                                       "border:1px solid black;\n"
                                       "\n"
                                       "")
        self.printWindow.setObjectName("printWindow")
        self.verticalLayout.addWidget(self.printWindow)
        self.gridLayout_2.addWidget(self.solution, 1, 2, 2, 1)
        self.control = QtWidgets.QWidget(self.container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.control.sizePolicy().hasHeightForWidth())
        self.control.setSizePolicy(sizePolicy)
        self.control.setStyleSheet("")
        self.control.setObjectName("control")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.control)
        self.gridLayout_4.setContentsMargins(20, 20, 20, 20)
        self.gridLayout_4.setSpacing(20)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.options = QtWidgets.QLabel(self.control)
        self.options.setMinimumSize(QtCore.QSize(0, 20))
        self.options.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        self.options.setFont(font)
        self.options.setAlignment(QtCore.Qt.AlignCenter)
        self.options.setObjectName("options")
        self.gridLayout_4.addWidget(self.options, 0, 0, 1, 2)
        self.isSolvableButton = QtWidgets.QPushButton(self.control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.isSolvableButton.sizePolicy().hasHeightForWidth())
        self.isSolvableButton.setSizePolicy(sizePolicy)
        self.isSolvableButton.setMinimumSize(QtCore.QSize(100, 50))
        self.isSolvableButton.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        self.isSolvableButton.setFont(font)
        self.isSolvableButton.setStyleSheet("background-color:#00aaff;\n"
                                            "color:#ffffff;\n"
                                            "\n"
                                            "border-style: outset;\n"
                                            "border-width: 1px;\n"
                                            "border-radius: 15px;\n"
                                            "border-color: black;\n"
                                            "padding: 4px;")
        self.isSolvableButton.setShortcut("")
        self.isSolvableButton.setObjectName("isSolvableButton")
        self.gridLayout_4.addWidget(self.isSolvableButton, 1, 1, 1, 1)
        self.appResetButton = QtWidgets.QPushButton(self.control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.appResetButton.sizePolicy().hasHeightForWidth())
        self.appResetButton.setSizePolicy(sizePolicy)
        self.appResetButton.setMinimumSize(QtCore.QSize(100, 50))
        self.appResetButton.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        self.appResetButton.setFont(font)
        self.appResetButton.setStyleSheet("background-color:#00aaff;\n"
                                          "color:#ffffff;\n"
                                          "\n"
                                          "border-style: outset;\n"
                                          "border-width: 1px;\n"
                                          "border-radius: 15px;\n"
                                          "border-color: black;\n"
                                          "padding: 4px;")
        self.appResetButton.setAutoDefault(True)
        self.appResetButton.setObjectName("appResetButton")
        self.gridLayout_4.addWidget(self.appResetButton, 2, 1, 1, 1)
        self.findSolutionButton = QtWidgets.QPushButton(self.control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.findSolutionButton.sizePolicy().hasHeightForWidth())
        self.findSolutionButton.setSizePolicy(sizePolicy)
        self.findSolutionButton.setMinimumSize(QtCore.QSize(100, 50))
        self.findSolutionButton.setMaximumSize(QtCore.QSize(200, 100))
        self.findSolutionButton.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        self.findSolutionButton.setFont(font)
        self.findSolutionButton.setAutoFillBackground(False)
        self.findSolutionButton.setStyleSheet("background-color:#00aaff;\n"
                                              "color:#ffffff;\n"
                                              "\n"
                                              "border-style: outset;\n"
                                              "border-width: 1px;\n"
                                              "border-radius: 15px;\n"
                                              "border-color: black;\n"
                                              "padding: 4px;")
        self.findSolutionButton.setAutoDefault(True)
        self.findSolutionButton.setObjectName("findSolutionButton")
        self.gridLayout_4.addWidget(self.findSolutionButton, 1, 0, 1, 1)
        self.simulationButton = QtWidgets.QPushButton(self.control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.simulationButton.sizePolicy().hasHeightForWidth())
        self.simulationButton.setSizePolicy(sizePolicy)
        self.simulationButton.setMinimumSize(QtCore.QSize(100, 50))
        self.simulationButton.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.simulationButton.setFont(font)
        self.simulationButton.setStyleSheet("background-color:#00aaff;\n"
                                            "color:#ffffff;\n"
                                            "\n"
                                            "border-style: outset;\n"
                                            "border-width: 1px;\n"
                                            "border-radius: 15px;\n"
                                            "border-color: black;\n"
                                            "padding: 4px;")
        self.simulationButton.setCheckable(True)
        self.simulationButton.setChecked(False)
        self.simulationButton.setAutoDefault(True)
        self.simulationButton.setObjectName("simulationButton")
        self.gridLayout_4.addWidget(self.simulationButton, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.control, 0, 2, 1, 1)
        self.initial_state = QtWidgets.QWidget(self.container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.initial_state.sizePolicy().hasHeightForWidth())
        self.initial_state.setSizePolicy(sizePolicy)
        self.initial_state.setStyleSheet("border: none;")
        self.initial_state.setObjectName("initial_state")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.initial_state)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.init = QtWidgets.QWidget(self.initial_state)
        self.init.setMinimumSize(QtCore.QSize(200, 200))
        self.init.setObjectName("init")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.init)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lineEdit = QtWidgets.QLineEdit(self.init)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(22)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background: #ffffff; \n"
                                    "border: 2px solid red;;")
        self.lineEdit.setMaxLength(1)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_6.addWidget(self.lineEdit, 2, 0, 1, 1)
        self.initLabel = QtWidgets.QLabel(self.init)
        self.initLabel.setMinimumSize(QtCore.QSize(0, 20))
        self.initLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        self.initLabel.setFont(font)
        self.initLabel.setTextFormat(QtCore.Qt.AutoText)
        self.initLabel.setScaledContents(False)
        self.initLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.initLabel.setObjectName("initLabel")
        self.gridLayout_6.addWidget(self.initLabel, 1, 0, 1, 3)
        self.i7 = QtWidgets.QLineEdit(self.init)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(22)
        self.i7.setFont(font)
        self.i7.setAutoFillBackground(False)
        self.i7.setStyleSheet("background: #ffffff; \n"
                              "border: 2px solid red;;")
        self.i7.setMaxLength(1)
        self.i7.setAlignment(QtCore.Qt.AlignCenter)
        self.i7.setClearButtonEnabled(False)
        self.i7.setObjectName("i7")
        self.gridLayout_6.addWidget(self.i7, 4, 1, 1, 1)
        self.i6 = QtWidgets.QLineEdit(self.init)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(22)
        self.i6.setFont(font)
        self.i6.setAutoFillBackground(False)
        self.i6.setStyleSheet("background: #ffffff; \n"
                              "border: 2px solid red;;")
        self.i6.setMaxLength(1)
        self.i6.setAlignment(QtCore.Qt.AlignCenter)
        self.i6.setClearButtonEnabled(False)
        self.i6.setObjectName("i6")
        self.gridLayout_6.addWidget(self.i6, 4, 0, 1, 1)
        self.i1 = QtWidgets.QLineEdit(self.init)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(22)
        self.i1.setFont(font)
        self.i1.setAutoFillBackground(False)
        self.i1.setStyleSheet("background: #ffffff; \n"
                              "border: 2px solid red;;")
        self.i1.setMaxLength(1)
        self.i1.setAlignment(QtCore.Qt.AlignCenter)
        self.i1.setClearButtonEnabled(False)
        self.i1.setObjectName("i1")
        self.gridLayout_6.addWidget(self.i1, 2, 1, 1, 1)
        self.i2 = QtWidgets.QLineEdit(self.init)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(22)
        self.i2.setFont(font)
        self.i2.setAutoFillBackground(False)
        self.i2.setStyleSheet("background: #ffffff; \n"
                              "border: 2px solid red;;")
        self.i2.setMaxLength(1)
        self.i2.setAlignment(QtCore.Qt.AlignCenter)
        self.i2.setClearButtonEnabled(False)
        self.i2.setObjectName("i2")
        self.gridLayout_6.addWidget(self.i2, 2, 2, 1, 1)
        self.i4 = QtWidgets.QLineEdit(self.init)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(22)
        self.i4.setFont(font)
        self.i4.setAutoFillBackground(False)
        self.i4.setStyleSheet("background: #ffffff; \n"
                              "border: 2px solid red;;")
        self.i4.setMaxLength(1)
        self.i4.setAlignment(QtCore.Qt.AlignCenter)
        self.i4.setClearButtonEnabled(False)
        self.i4.setObjectName("i4")
        self.gridLayout_6.addWidget(self.i4, 3, 1, 1, 1)
        self.i5 = QtWidgets.QLineEdit(self.init)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(22)
        self.i5.setFont(font)
        self.i5.setAutoFillBackground(False)
        self.i5.setStyleSheet("background: #ffffff; \n"
                              "border: 2px solid red;;")
        self.i5.setMaxLength(1)
        self.i5.setAlignment(QtCore.Qt.AlignCenter)
        self.i5.setClearButtonEnabled(False)
        self.i5.setObjectName("i5")
        self.gridLayout_6.addWidget(self.i5, 3, 2, 1, 1)
        self.i8 = QtWidgets.QLineEdit(self.init)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(22)
        self.i8.setFont(font)
        self.i8.setAutoFillBackground(False)
        self.i8.setStyleSheet("background: #ffffff; \n"
                              "border: 2px solid red;;")
        self.i8.setMaxLength(1)
        self.i8.setAlignment(QtCore.Qt.AlignCenter)
        self.i8.setClearButtonEnabled(False)
        self.i8.setObjectName("i8")
        self.gridLayout_6.addWidget(self.i8, 4, 2, 1, 1)
        self.i3 = QtWidgets.QLineEdit(self.init)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(22)
        self.i3.setFont(font)
        self.i3.setAutoFillBackground(False)
        self.i3.setStyleSheet("background: #ffffff; \n"
                              "border: 2px solid red;;")
        self.i3.setMaxLength(1)
        self.i3.setAlignment(QtCore.Qt.AlignCenter)
        self.i3.setClearButtonEnabled(False)
        self.i3.setObjectName("i3")
        self.gridLayout_6.addWidget(self.i3, 3, 0, 1, 1)
        self.horizontalLayout.addWidget(self.init)
        self.gridLayout_2.addWidget(self.initial_state, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.container, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 829, 21))
        self.menubar.setObjectName("menubar")
        self.menuSave = QtWidgets.QMenu(self.menubar)
        self.menuSave.setObjectName("menuSave")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.menuSave.addAction(self.actionSave)
        self.menuSave.addAction(self.actionCopy)
        self.menubar.addAction(self.menuSave.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit, self.i1)
        MainWindow.setTabOrder(self.i1, self.i2)
        MainWindow.setTabOrder(self.i2, self.i3)
        MainWindow.setTabOrder(self.i3, self.i4)
        MainWindow.setTabOrder(self.i4, self.i5)
        MainWindow.setTabOrder(self.i5, self.i6)
        MainWindow.setTabOrder(self.i6, self.i7)
        MainWindow.setTabOrder(self.i7, self.i8)
        MainWindow.setTabOrder(self.i8, self.g0)
        MainWindow.setTabOrder(self.g0, self.g1)
        MainWindow.setTabOrder(self.g1, self.g2)
        MainWindow.setTabOrder(self.g2, self.g3)
        MainWindow.setTabOrder(self.g3, self.g4)
        MainWindow.setTabOrder(self.g4, self.g5)
        MainWindow.setTabOrder(self.g5, self.g6)
        MainWindow.setTabOrder(self.g6, self.g7)
        MainWindow.setTabOrder(self.g7, self.g8)
        MainWindow.setTabOrder(self.g8, self.findSolutionButton)
        MainWindow.setTabOrder(self.findSolutionButton, self.isSolvableButton)
        MainWindow.setTabOrder(self.isSolvableButton, self.simulationButton)
        MainWindow.setTabOrder(self.simulationButton, self.appResetButton)
        MainWindow.setTabOrder(self.appResetButton, self.previousButton)
        MainWindow.setTabOrder(self.previousButton, self.pauseButton)
        MainWindow.setTabOrder(self.pauseButton, self.startButton)
        MainWindow.setTabOrder(self.startButton, self.resetButton)
        MainWindow.setTabOrder(self.resetButton, self.nextButton)
        MainWindow.setTabOrder(self.nextButton, self.toggleManualControl)
        MainWindow.setTabOrder(self.toggleManualControl, self.printWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.goalLabel.setText(_translate("MainWindow", "Goal State"))
        self.toggleManualControl.setText(_translate("MainWindow", "Switch between states Manually"))
        self.nextButton.setText(_translate("MainWindow", "Next"))
        self.previousButton.setText(_translate("MainWindow", "Previous"))
        self.pauseButton.setText(_translate("MainWindow", "Pause"))
        self.resetButton.setText(_translate("MainWindow", "Reset"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.out6.setText(_translate("MainWindow", "0"))
        self.out0.setText(_translate("MainWindow", "0"))
        self.out2.setText(_translate("MainWindow", "0"))
        self.out1.setText(_translate("MainWindow", "0"))
        self.out3.setText(_translate("MainWindow", "0"))
        self.out4.setText(_translate("MainWindow", "0"))
        self.out5.setText(_translate("MainWindow", "0"))
        self.out7.setText(_translate("MainWindow", "0"))
        self.out8.setText(_translate("MainWindow", "0"))
        self.label.setText(_translate("MainWindow", "Simulation Controls"))
        self.label_3.setText(_translate("MainWindow", "Output Window!"))
        self.printWindow.setHtml(_translate("MainWindow",
                                            "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                            "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                            "p, li { white-space: pre-wrap; }\n"
                                            "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                            "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    </p></body></html>"))
        self.options.setText(_translate("MainWindow", "Options"))
        self.isSolvableButton.setText(_translate("MainWindow", "Is Solvable?"))
        self.appResetButton.setText(_translate("MainWindow", "Reset"))
        self.findSolutionButton.setText(_translate("MainWindow", "Find Solution"))
        self.simulationButton.setText(_translate("MainWindow", "Simulation"))
        self.initLabel.setText(_translate("MainWindow", "Initial State"))
        self.menuSave.setTitle(_translate("MainWindow", "Options"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
